/**
 * Aervox｜思隅 @aervox/worker — 日记生成 Worker（定时兜底路径）
 *
 * 规则依据：PRD §8（DiarySchedule/DiaryCycle/DiaryVersion）+ ADR-011。
 *
 * 与按需路径（对话工具 / POST generate-today）共用 @aervox/diary 生成单源：
 * - 素材 = 当日消息 + 当日记忆 + 学习目标 + 当日练习（collectDiaryMaterial）；
 * - AI 依据当天记忆与上下文、模仿人类写日记（Prompt/模板降级均在共享服务内）；
 * - 同日已存在日记则跳过（推进游标），避免与按需路径对同日唯一索引的冲突；
 * - localDate 统一服务器本地日期（localDateToday），修正既定 UTC 前缀偏差。
 */
import { and, eq, sql } from "drizzle-orm";
import {
  diarySchedules,
  type AervoxDatabase,
  type SqliteDiaryRepository,
  type SqliteLLMConfigRepository,
  type SqlitePlatformRepository,
  type SqliteOutboxRepository,
  type TenantContext,
} from "@aervox/database";
import {
  collectDiaryMaterial,
  createLlmDiaryModelPort,
  createRepoDiaryLlmConfigPort,
  DiaryGenerationService,
  generateDiaryId,
  localDateToday,
} from "@aervox/diary";

export interface DiaryGeneratorContext {
  db: AervoxDatabase;
  diaryRepo: SqliteDiaryRepository;
  llmConfigRepo: SqliteLLMConfigRepository;
  platformRepo: SqlitePlatformRepository;
  outboxRepo: SqliteOutboxRepository;
  workerId: string;
}

const DAY_MS = 24 * 60 * 60 * 1000;

/** 单次日记生成扫描；返回生成的日记数量 */
export async function runDiaryGenerationCycle(ctx: DiaryGeneratorContext): Promise<number> {
  const now = new Date().toISOString();

  // 跨租户只读：扫描到期且启用的计划
  const schedules = await ctx.db
    .select()
    .from(diarySchedules)
    .where(
      and(
        eq(diarySchedules.enabled, 1),
        sql`(${diarySchedules.nextRunAt} IS NULL OR ${diarySchedules.nextRunAt} <= ${now})`,
      ),
    )
    .limit(20);

  if (schedules.length === 0) return 0;

  const generation = new DiaryGenerationService({
    db: ctx.db,
    model: createLlmDiaryModelPort(createRepoDiaryLlmConfigPort(ctx.llmConfigRepo)),
  });

  let generated = 0;
  for (const schedule of schedules) {
    const tenant: TenantContext = {
      workspaceId: schedule.workspaceId,
      subjectUserId: schedule.subjectUserId,
    };
    // 服务器本地日期（与按需路径同一日期语义，避免同日错位）
    const localDate = localDateToday(new Date());

    try {
      // 0. 同日已存在（按需路径可能已生成）→ 跳过并推进游标，避免唯一索引冲突
      const existingDiary = await ctx.diaryRepo.getDiaryByDate(tenant, localDate);
      if (existingDiary) {
        await ctx.db
          .update(diarySchedules)
          .set({
            nextRunAt: new Date(Date.now() + DAY_MS).toISOString(),
            lastCutoffAt: now,
            updatedAt: now,
          })
          .where(eq(diarySchedules.id, schedule.id));
        continue;
      }

      // 1. 创建不可变周期（scheduleVersion=1）
      const cycle = await ctx.diaryRepo.createCycle(tenant, {
        id: generateDiaryId("cyc"),
        scheduleEpochId: schedule.scheduleEpochId,
        localDate,
        previousCutoffAt: schedule.lastCutoffAt ?? schedule.activeFrom,
        cutoffAt: now,
      });

      // 2. 汇总该窗口素材（跨租户只读：对话/记忆/目标/练习，与按需路径同源）
      const window = { startIso: cycle.previousCutoffAt, endIso: cycle.cutoffAt };
      const material = await collectDiaryMaterial(ctx.db, tenant, window);
      const materialCount =
        material.messages.length + material.memories.length + material.goals.length;

      // 3. 生成日记（LLM 或模板降级，均在共享服务内决策）
      const draft = await generation.generate(tenant, { localDate, window });

      // 4. 同一事务发布日记 + 周期状态 + Outbox + 创建日记版本
      const published = await ctx.diaryRepo.publishDiaryWithCycle(tenant, {
        cycleId: cycle.id,
        diary: {
          id: generateDiaryId("diary"),
          localDate,
          title: draft.title,
          content: draft.content,
          autoGenerated: 1,
        },
        expectedScheduleVersion: 1,
        outboxEvent: {
          id: generateDiaryId("outbox"),
          eventType: "diary.published",
          idempotencyKey: generateDiaryId("idem_diary"),
          payload: { cycleId: cycle.id, localDate },
        },
      });
      await ctx.diaryRepo.createDiaryVersion(tenant, {
        id: generateDiaryId("dv"),
        diaryId: published.diary.id,
        perspective: "ai_generated",
        content: draft.content,
      });

      // 5. 推进计划游标（+1 天；自定义 cron 后续按 cutoffRule 计算）
      await ctx.db
        .update(diarySchedules)
        .set({
          nextRunAt: new Date(Date.now() + DAY_MS).toISOString(),
          lastCutoffAt: now,
          updatedAt: now,
        })
        .where(eq(diarySchedules.id, schedule.id));

      await ctx.platformRepo.createAuditRecord(tenant, {
        id: generateDiaryId("aud"),
        actorType: "system",
        actorId: `diary:${ctx.workerId}`,
        action: "diary.generated",
        subjectType: "diary_cycle",
        subjectId: cycle.id,
        metadata: { localDate, materialCount, generatedBy: draft.generatedBy },
      });
      generated += 1;
    } catch (err) {
      console.error(`[diary-generator] schedule ${schedule.id} failed:`, err);
    }
  }
  return generated;
}