/**
 * Aervox｜思隅 @aervox/database — 日记与调度周期 SQLite 仓储实现
 *
 * 规则依据：ADR-011 不可变周期、计划修订、CAS 乐观锁与 lease/fencing
 */
import { eq, and, sql } from "drizzle-orm";
import type { AervoxDatabase } from "../../client.js";
import {
  diaries,
  diaryCycles,
  diaryRunAttempts,
  diarySchedules,
  diaryVersions,
  diaryParagraphSources,
  diaryMaterialBuffers,
  outboxEvents,
} from "../../schema/index.js";
import { assertTenantContext, type TenantContext } from "../../tenant.js";
import type {
  IDiaryRepository,
  DiaryModel,
  DiaryCycleModel,
  DiaryScheduleModel,
  DiaryVersionModel,
  DiaryParagraphSourceModel,
  DiaryMaterialBufferModel,
} from "../types.js";

export class SqliteDiaryRepository implements IDiaryRepository {
  constructor(private readonly db: AervoxDatabase) {}

  async createCycle(
    tenant: TenantContext,
    cycleData: {
      id: string;
      scheduleEpochId: string;
      localDate: string;
      previousCutoffAt: string;
      cutoffAt: string;
      status?: string;
    },
  ): Promise<DiaryCycleModel> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();
    const [created] = await this.db
      .insert(diaryCycles)
      .values({
        id: cycleData.id,
        workspaceId: tenant.workspaceId,
        subjectUserId: tenant.subjectUserId,
        scheduleEpochId: cycleData.scheduleEpochId,
        localDate: cycleData.localDate,
        previousCutoffAt: cycleData.previousCutoffAt,
        cutoffAt: cycleData.cutoffAt,
        status: cycleData.status ?? "Scheduled",
        scheduleVersion: 1,
        fencingToken: 0,
        createdAt: now,
        updatedAt: now,
      })
      .returning();
    return created as DiaryCycleModel;
  }

  async getCycle(tenant: TenantContext, cycleId: string): Promise<DiaryCycleModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diaryCycles)
      .where(
        and(
          eq(diaryCycles.id, cycleId),
          eq(diaryCycles.workspaceId, tenant.workspaceId),
          eq(diaryCycles.subjectUserId, tenant.subjectUserId),
        ),
      );
    return (found as DiaryCycleModel) ?? null;
  }

  async claimCycleWithLease(
    tenant: TenantContext,
    params: {
      cycleId: string;
      workerId: string;
      leaseDurationMs: number;
      expectedScheduleVersion: number;
    },
  ): Promise<{ success: boolean; newScheduleVersion?: number; fencingToken?: number }> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();
    const leaseExpiresAt = new Date(Date.now() + params.leaseDurationMs).toISOString();

    return await this.db.transaction(async (tx) => {
      // 执行 CAS 乐观锁更新 scheduleVersion
      const [updated] = await tx
        .update(diaryCycles)
        .set({
          status: "Claimed",
          scheduleVersion: sql`${diaryCycles.scheduleVersion} + 1`,
          fencingToken: sql`${diaryCycles.fencingToken} + 1`,
          updatedAt: now,
        })
        .where(
          and(
            eq(diaryCycles.id, params.cycleId),
            eq(diaryCycles.workspaceId, tenant.workspaceId),
            eq(diaryCycles.subjectUserId, tenant.subjectUserId),
            eq(diaryCycles.scheduleVersion, params.expectedScheduleVersion),
          ),
        )
        .returning();

      if (!updated) {
        return { success: false };
      }

      // 记录 Worker 执行尝试
      const attemptId = `att_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
      await tx.insert(diaryRunAttempts).values({
        id: attemptId,
        cycleId: params.cycleId,
        scheduleVersion: updated.scheduleVersion,
        workerId: params.workerId,
        attempt: updated.fencingToken,
        status: "Claimed",
        leaseExpiresAt,
        createdAt: now,
      });

      return {
        success: true,
        newScheduleVersion: updated.scheduleVersion,
        fencingToken: updated.fencingToken,
      };
    });
  }

  async publishDiaryWithCycle(
    tenant: TenantContext,
    params: {
      cycleId: string;
      diary: { id: string; localDate: string; title: string; content: string; autoGenerated?: number };
      expectedScheduleVersion: number;
      outboxEvent?: { id: string; eventType: string; idempotencyKey: string; payload: unknown };
    },
  ): Promise<{ diary: DiaryModel; cycle: DiaryCycleModel }> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();

    return await this.db.transaction(async (tx) => {
      // 1. 插入日记实体（SQLite 条件唯一索引防护重复自动日记）
      const [createdDiary] = await tx
        .insert(diaries)
        .values({
          id: params.diary.id,
          workspaceId: tenant.workspaceId,
          subjectUserId: tenant.subjectUserId,
          localDate: params.diary.localDate,
          autoGenerated: params.diary.autoGenerated ?? 1,
          title: params.diary.title,
          content: params.diary.content,
          version: 1,
          createdAt: now,
          updatedAt: now,
        })
        .returning();

      if (!createdDiary) {
        throw new Error("Failed to insert diary record");
      }

      // 2. CAS 更新周期状态为 Published 并绑定 diaryId
      const [updatedCycle] = await tx
        .update(diaryCycles)
        .set({
          status: "Published",
          diaryId: createdDiary.id,
          scheduleVersion: sql`${diaryCycles.scheduleVersion} + 1`,
          updatedAt: now,
        })
        .where(
          and(
            eq(diaryCycles.id, params.cycleId),
            eq(diaryCycles.workspaceId, tenant.workspaceId),
            eq(diaryCycles.subjectUserId, tenant.subjectUserId),
            eq(diaryCycles.scheduleVersion, params.expectedScheduleVersion),
          ),
        )
        .returning();

      if (!updatedCycle) {
        throw new Error(
          `Failed to publish diary: cycle ${params.cycleId} version mismatch (expected ${params.expectedScheduleVersion})`,
        );
      }

      // 3. 在同一事务写入 Outbox
      if (params.outboxEvent) {
        await tx.insert(outboxEvents).values({
          id: params.outboxEvent.id,
          workspaceId: tenant.workspaceId,
          subjectUserId: tenant.subjectUserId,
          idempotencyKey: params.outboxEvent.idempotencyKey,
          eventType: params.outboxEvent.eventType,
          payload: params.outboxEvent.payload,
          status: "pending",
          createdAt: now,
        });
      }

      return {
        diary: createdDiary as DiaryModel,
        cycle: updatedCycle as DiaryCycleModel,
      };
    });
  }

  async getDiaryByDate(tenant: TenantContext, localDate: string): Promise<DiaryModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diaries)
      .where(
        and(
          eq(diaries.workspaceId, tenant.workspaceId),
          eq(diaries.subjectUserId, tenant.subjectUserId),
          eq(diaries.localDate, localDate),
        ),
      );
    return (found as DiaryModel) ?? null;
  }

  async listDiaries(tenant: TenantContext, limit: number): Promise<DiaryModel[]> {
    assertTenantContext(tenant);
    const rows = await this.db
      .select()
      .from(diaries)
      .where(
        and(
          eq(diaries.workspaceId, tenant.workspaceId),
          eq(diaries.subjectUserId, tenant.subjectUserId),
        ),
      )
      .orderBy(diaries.localDate)
      .limit(Math.max(1, Math.min(100, limit)));
    return rows as DiaryModel[];
  }

  // ============ MVP+ 补齐（PRD §8）：计划主实体 / 版本 / 段落来源 / 素材缓冲 ============

  async createDiarySchedule(
    tenant: TenantContext,
    scheduleData: {
      id: string;
      scheduleEpochId: string;
      activeFrom: string;
      initialWindowStart: string;
      cutoffRule: string;
      bufferMinutes?: number;
      contentScopes?: unknown;
      quietHours?: unknown;
      enabled?: number;
      nextRunAt?: string;
    },
  ): Promise<DiaryScheduleModel> {
    assertTenantContext(tenant);
    const now = new Date().toISOString();
    const [created] = await this.db
      .insert(diarySchedules)
      .values({
        id: scheduleData.id,
        workspaceId: tenant.workspaceId,
        subjectUserId: tenant.subjectUserId,
        enabled: scheduleData.enabled ?? 1,
        scheduleEpochId: scheduleData.scheduleEpochId,
        activeFrom: scheduleData.activeFrom,
        initialWindowStart: scheduleData.initialWindowStart,
        cutoffRule: scheduleData.cutoffRule,
        bufferMinutes: scheduleData.bufferMinutes ?? 0,
        contentScopes: scheduleData.contentScopes ?? null,
        quietHours: scheduleData.quietHours ?? null,
        nextRunAt: scheduleData.nextRunAt ?? null,
        version: 1,
        createdAt: now,
        updatedAt: now,
      })
      .returning();
    return created as DiaryScheduleModel;
  }

  async getDiarySchedule(tenant: TenantContext, id: string): Promise<DiaryScheduleModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diarySchedules)
      .where(
        and(
          eq(diarySchedules.id, id),
          eq(diarySchedules.workspaceId, tenant.workspaceId),
          eq(diarySchedules.subjectUserId, tenant.subjectUserId),
        ),
      );
    return (found as DiaryScheduleModel) ?? null;
  }

  async getActiveDailySchedule(tenant: TenantContext): Promise<DiaryScheduleModel | null> {
    assertTenantContext(tenant);
    const [found] = await this.db
      .select()
      .from(diarySchedules)
      .where(
        and(
          eq(diarySchedules.workspaceId, tenant.workspaceId),
          eq(diarySchedules.subjectUserId, tenant.subjectUserId),
          eq(diarySchedules.enabled, 1),
          eq(diarySchedules.cutoffRule, "daily"),
        ),
      )
      .limit(1);
    return (found as DiaryScheduleModel) ?? null;
  }

  async createDiaryVersion(
    tenant: TenantContext,
    versionData: {
      id: string;
      diaryId: string;
      perspective: string;
      content: string;
      modelRunId?: string | null;
    },
  ): Promise<DiaryVersionModel> {
    assertTenantContext(tenant);
    // 校验日记属于当前租户
    const [diary] = await this.db
      .select()
      .from(diaries)
      .where(
        and(
          eq(diaries.id, versionData.diaryId),
          eq(diaries.workspaceId, tenant.workspaceId),
          eq(diaries.subjectUserId, tenant.subjectUserId),
        ),
      );
    if (!diary) throw new Error(`Diary ${versionData.diaryId} not found in tenant`);
    const [created] = await this.db
      .insert(diaryVersions)
      .values({
        id: versionData.id,
        diaryId: versionData.diaryId,
        perspective: versionData.perspective,
        content: versionData.content,
        modelRunId: versionData.modelRunId ?? null,
        createdAt: new Date().toISOString(),
      })
      .returning();
    return created as DiaryVersionModel;
  }

  /**
   * 更新日记主行内容（改写路径）：内容指向最新版本，version 递增，状态转 edited。
   * 历史版本不覆盖（createDiaryVersion 已落版本账本）；此处仅推进主行指针。
   */
  async updateDiaryContent(
    tenant: TenantContext,
    diaryId: string,
    update: { title?: string; content: string },
  ): Promise<DiaryModel> {
    assertTenantContext(tenant);
    const [existing] = await this.db
      .select()
      .from(diaries)
      .where(
        and(
          eq(diaries.id, diaryId),
          eq(diaries.workspaceId, tenant.workspaceId),
          eq(diaries.subjectUserId, tenant.subjectUserId),
        ),
      );
    if (!existing) throw new Error(`Diary ${diaryId} not found in tenant`);
    const now = new Date().toISOString();
    const [updated] = await this.db
      .update(diaries)
      .set({
        title: update.title ?? existing.title,
        content: update.content,
        version: existing.version + 1,
        status: "edited",
        updatedAt: now,
      })
      .where(eq(diaries.id, diaryId))
      .returning();
    return updated as DiaryModel;
  }

  async createDiaryParagraphSource(
    sourceData: {
      id: string;
      diaryVersionId: string;
      paragraphIndex: number;
      sourceArtifactId: string;
      sourceRevisionId: string;
      permissionSnapshot?: unknown;
    },
  ): Promise<DiaryParagraphSourceModel> {
    const [created] = await this.db
      .insert(diaryParagraphSources)
      .values({
        id: sourceData.id,
        diaryVersionId: sourceData.diaryVersionId,
        paragraphIndex: sourceData.paragraphIndex,
        sourceArtifactId: sourceData.sourceArtifactId,
        sourceRevisionId: sourceData.sourceRevisionId,
        permissionSnapshot: sourceData.permissionSnapshot ?? null,
      })
      .returning();
    return created as DiaryParagraphSourceModel;
  }

  async createDiaryMaterialBuffer(
    tenant: TenantContext,
    bufferData: {
      id: string;
      cycleId: string;
      sourceArtifactId: string;
      sourceRevisionId: string;
      occurredAt: string;
      ingestedAt: string;
      expiresAt: string;
      ephemeralSnapshot?: unknown;
      permissionSnapshot?: unknown;
    },
  ): Promise<DiaryMaterialBufferModel> {
    assertTenantContext(tenant);
    const [created] = await this.db
      .insert(diaryMaterialBuffers)
      .values({
        id: bufferData.id,
        cycleId: bufferData.cycleId,
        workspaceId: tenant.workspaceId,
        subjectUserId: tenant.subjectUserId,
        sourceArtifactId: bufferData.sourceArtifactId,
        sourceRevisionId: bufferData.sourceRevisionId,
        occurredAt: bufferData.occurredAt,
        ingestedAt: bufferData.ingestedAt,
        ephemeralSnapshot: bufferData.ephemeralSnapshot ?? null,
        permissionSnapshot: bufferData.permissionSnapshot ?? null,
        expiresAt: bufferData.expiresAt,
        status: "buffered",
      })
      .returning();
    return created as DiaryMaterialBufferModel;
  }
}
