/**
 * Aervox｜思隅 @aervox/api — 日记应用服务（按需/手动触发共用）
 *
 * 供对话工具（aervox_diary_write）与 REST（POST /v1/diaries/generate-today）复用：
 * - ensureTodayDiary：首开/每日取回幂等路径——当日已有直接返回 existing，否则生成新建；
 * - rewriteTodayDiary：手动「让思思现在写」/对话触发——当日已有落 rewrite 版本并推进主行，否则新建；
 * - ensureDefaultSchedule：懒创建租户默认每日计划（Worker 定时路径兜底）。
 */
import type { SqliteDiaryRepository, TenantContext } from "@aervox/database";
import {
  DiaryGenerationService,
  generateDiaryId,
  localDateToday,
  todayWindow,
} from "@aervox/diary";

export interface DiaryApplicationServiceDeps {
  diaryRepo: SqliteDiaryRepository;
  generation: DiaryGenerationService;
}

export interface TodayDiaryResult {
  diaryId: string;
  localDate: string;
  title: string;
  content: string;
  mode: "created" | "rewritten" | "existing";
  generatedBy: "llm" | "template";
  materialCount: number;
}

/** 模板日记正文带有诚实标注标记；据此回推历史日记的生成方式（仅展示用） */
const TEMPLATE_MARKER = "（本篇为非 LLM 模式的模板日记";
function detectGeneratedBy(content: string): "llm" | "template" {
  return content.includes(TEMPLATE_MARKER) ? "template" : "llm";
}

const DAY_MS = 24 * 60 * 60 * 1000;

export class DiaryApplicationService {
  constructor(private readonly deps: DiaryApplicationServiceDeps) {}

  /** 幂等取回当日日记：已有直接返回（existing），无则生成并新建（on-demand 周期发布） */
  async ensureTodayDiary(tenant: TenantContext, focus?: string): Promise<TodayDiaryResult> {
    const now = new Date();
    const localDate = localDateToday(now);
    const existing = await this.deps.diaryRepo.getDiaryByDate(tenant, localDate);
    if (existing) {
      return {
        diaryId: existing.id,
        localDate,
        title: existing.title,
        content: existing.content,
        mode: "existing",
        generatedBy: detectGeneratedBy(existing.content),
        materialCount: 0,
      };
    }
    return this.generateAndPublish(tenant, localDate, now, focus);
  }

  /** 手动/对话触发当日日记：已有则改写（rewrite 版本，历史不覆盖），无则新建 */
  async rewriteTodayDiary(tenant: TenantContext, focus?: string): Promise<TodayDiaryResult> {
    const now = new Date();
    const localDate = localDateToday(now);
    const existing = await this.deps.diaryRepo.getDiaryByDate(tenant, localDate);
    if (existing) {
      return this.rewriteExisting(tenant, existing.id, localDate, now, focus);
    }
    return this.generateAndPublish(tenant, localDate, now, focus);
  }

  /** 懒创建租户默认每日计划（幂等）：Worker 定时路径由此激活，nextRunAt=+24h 防止当日立即重复执行 */
  async ensureDefaultSchedule(tenant: TenantContext): Promise<void> {
    const existing = await this.deps.diaryRepo.getActiveDailySchedule(tenant);
    if (existing) return;
    const now = new Date();
    const localDate = localDateToday(now);
    await this.deps.diaryRepo.createDiarySchedule(tenant, {
      id: generateDiaryId("ds"),
      scheduleEpochId: "default:daily",
      activeFrom: now.toISOString(),
      initialWindowStart: `${localDate}T00:00:00`,
      cutoffRule: "daily",
      bufferMinutes: 0,
      nextRunAt: new Date(Date.now() + DAY_MS).toISOString(),
    });
  }

  /** 生成草稿并走事务发布（新建 on-demand 周期 + outbox + 版本）；与 Worker 定时路径同协议 */
  private async generateAndPublish(
    tenant: TenantContext,
    localDate: string,
    now: Date,
    focus?: string,
  ): Promise<TodayDiaryResult> {
    const { diaryRepo, generation } = this.deps;
    const draft = await generation.generate(tenant, {
      localDate,
      window: todayWindow(now),
      focus,
    });
    const cycle = await diaryRepo.createCycle(tenant, {
      id: generateDiaryId("cyc"),
      scheduleEpochId: `on_demand:${localDate}`,
      localDate,
      previousCutoffAt: `${localDate}T00:00:00`,
      cutoffAt: now.toISOString(),
    });
    const published = await diaryRepo.publishDiaryWithCycle(tenant, {
      cycleId: cycle.id,
      diary: {
        id: generateDiaryId("diary"),
        localDate,
        title: draft.title,
        content: draft.content,
        autoGenerated: 1,
      },
      expectedScheduleVersion: 1,
      outboxEvent: {
        id: generateDiaryId("outbox"),
        eventType: "diary.published",
        idempotencyKey: generateDiaryId("idem_diary_ondemand"),
        payload: { cycleId: cycle.id, localDate, trigger: "on_demand" },
      },
    });
    await diaryRepo.createDiaryVersion(tenant, {
      id: generateDiaryId("dv"),
      diaryId: published.diary.id,
      perspective: "ai_generated",
      content: draft.content,
    });
    return {
      diaryId: published.diary.id,
      localDate,
      title: draft.title,
      content: draft.content,
      mode: "created",
      generatedBy: draft.generatedBy,
      materialCount: draft.materialCount,
    };
  }

  /** 已有当日日记 → 新版本 + 主行推进（不覆盖历史版本） */
  private async rewriteExisting(
    tenant: TenantContext,
    diaryId: string,
    localDate: string,
    now: Date,
    focus?: string,
  ): Promise<TodayDiaryResult> {
    const { diaryRepo, generation } = this.deps;
    const draft = await generation.generate(tenant, {
      localDate,
      window: todayWindow(now),
      focus,
    });
    await diaryRepo.createDiaryVersion(tenant, {
      id: generateDiaryId("dv"),
      diaryId,
      perspective: "rewrite",
      content: draft.content,
    });
    const updated = await diaryRepo.updateDiaryContent(tenant, diaryId, {
      title: draft.title,
      content: draft.content,
    });
    return {
      diaryId: updated.id,
      localDate,
      title: draft.title,
      content: draft.content,
      mode: "rewritten",
      generatedBy: draft.generatedBy,
      materialCount: draft.materialCount,
    };
  }
}